import Sidebar from '@/components/ui.custom/sidebar';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Providers } from './providers';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});

const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
									   children,
								   }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body
			className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-700 dark:text-gray-300`}
		>
		<Providers>
			<div className="flex min-h-screen flex-col md:flex-row">
				{/* Sidebar */}
				<Sidebar />

				{/* Main Content */}
				<main className="flex-1 p-4 md:p-8 md:ml-64 transition-all duration-300 bg-gray-50 dark:bg-gray-900">
					<div className="max-w-7xl mx-auto w-full">{children}</div>
				</main>
			</div>
		</Providers>
		</body>
		</html>
	);
}